In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
import tensorflow as tf
import keras
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from tensorflow.keras import layers
from keras.layers import Dense, BatchNormalization, Dropout, Flatten, Conv2D, MaxPooling2D

In [2]:
wine=pd.read_csv("C:/Users/User/Desktop/2024-1/ESAA/미니프로젝트2_와인품질분류/train.csv")

In [3]:
wine=pd.get_dummies(data=wine, columns=['type'], prefix=['type'])
wine=wine.astype(float)

In [4]:
wine

index  quality  fixed acidity  volatile acidity  citric acid  \
0        0.0      5.0            5.6             0.695         0.06   
1        1.0      5.0            8.8             0.610         0.14   
2        2.0      5.0            7.9             0.210         0.39   
3        3.0      6.0            7.0             0.210         0.31   
4        4.0      6.0            7.8             0.400         0.26   
...      ...      ...            ...               ...          ...   
5492  5492.0      5.0            7.7             0.150         0.29   
5493  5493.0      6.0            6.3             0.180         0.36   
5494  5494.0      7.0            7.8             0.150         0.34   
5495  5495.0      5.0            6.6             0.410         0.31   
5496  5496.0      6.0            7.0             0.350         0.17   

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0   
1                2.4      0.067                 10.0                  42.0   
2                2.0      0.057                 21.0                 138.0   
3                6.0      0.046                 29.0                 108.0   
4                9.5      0.059                 32.0                 178.0   
...              ...        ...                  ...                   ...   
5492             1.3      0.029                 10.0                  64.0   
5493             1.2      0.034                 26.0                 111.0   
5494             1.1      0.035                 31.0                  93.0   
5495             1.6      0.042                 18.0                 101.0   
5496             1.1      0.049                  7.0                 119.0   

      density    pH  sulphates  alcohol  type_red  type_white  
0     0.99432  3.44       0.44     10.2       0.0         1.0  
1     0.99690  3.19       0.59      9.5       1.0         0.0  
2     0.99176  3.05       0.52     10.9       0.0         1.0  
3     0.99390  3.26       0.50     10.8       0.0         1.0  
4     0.99550  3.04       0.43     10.9       0.0         1.0  
...       ...   ...        ...      ...       ...         ...  
5492  0.99320  3.35       0.39     10.1       0.0         1.0  
5493  0.99074  3.16       0.51     11.0       0.0         1.0  
5494  0.99096  3.07       0.72     11.3       0.0         1.0  
5495  0.99195  3.13       0.41     10.5       0.0         1.0  
5496  0.99297  3.13       0.36      9.7       0.0         1.0  

[5497 rows x 15 columns]

In [5]:
X=wine.iloc[:, :-2]
X

index  quality  fixed acidity  volatile acidity  citric acid  \
0        0.0      5.0            5.6             0.695         0.06   
1        1.0      5.0            8.8             0.610         0.14   
2        2.0      5.0            7.9             0.210         0.39   
3        3.0      6.0            7.0             0.210         0.31   
4        4.0      6.0            7.8             0.400         0.26   
...      ...      ...            ...               ...          ...   
5492  5492.0      5.0            7.7             0.150         0.29   
5493  5493.0      6.0            6.3             0.180         0.36   
5494  5494.0      7.0            7.8             0.150         0.34   
5495  5495.0      5.0            6.6             0.410         0.31   
5496  5496.0      6.0            7.0             0.350         0.17   

      residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0                6.8      0.042                  9.0                  84.0   
1                2.4      0.067                 10.0                  42.0   
2                2.0      0.057                 21.0                 138.0   
3                6.0      0.046                 29.0                 108.0   
4                9.5      0.059                 32.0                 178.0   
...              ...        ...                  ...                   ...   
5492             1.3      0.029                 10.0                  64.0   
5493             1.2      0.034                 26.0                 111.0   
5494             1.1      0.035                 31.0                  93.0   
5495             1.6      0.042                 18.0                 101.0   
5496             1.1      0.049                  7.0                 119.0   

      density    pH  sulphates  alcohol  
0     0.99432  3.44       0.44     10.2  
1     0.99690  3.19       0.59      9.5  
2     0.99176  3.05       0.52     10.9  
3     0.99390  3.26       0.50     10.8  
4     0.99550  3.04       0.43     10.9  
...       ...   ...        ...      ...  
5492  0.99320  3.35       0.39     10.1  
5493  0.99074  3.16       0.51     11.0  
5494  0.99096  3.07       0.72     11.3  
5495  0.99195  3.13       0.41     10.5  
5496  0.99297  3.13       0.36      9.7  

[5497 rows x 13 columns]

In [6]:
Y=wine.iloc[:, -2:]
Y

type_red  type_white
0          0.0         1.0
1          1.0         0.0
2          0.0         1.0
3          0.0         1.0
4          0.0         1.0
...        ...         ...
5492       0.0         1.0
5493       0.0         1.0
5494       0.0         1.0
5495       0.0         1.0
5496       0.0         1.0

[5497 rows x 2 columns]

In [7]:
X_train, X_test, y_train, y_test=train_test_split(X, Y, test_size=0.2, random_state=22)

In [8]:
standard_scaler=preprocessing.StandardScaler()
stan_fit=standard_scaler.fit(X_train)
X_train_stan=stan_fit.transform(X_train)
X_test_stan=stan_fit.transform(X_test)

In [9]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(units=32, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=2, activation='relu')
])
model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

C:\Users\User\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 2)                   │              34 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,010 (3.95 KB)

 Trainable params: 1,010 (3.95 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

In [11]:
history=model.fit(X_train_stan, y_train, epochs=10, batch_size=32, validation_split=0.25)

Epoch 1/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2353 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 2/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.2504 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 3/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - accuracy: 0.2434 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 4/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.2550 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 5/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.2427 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 6/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - accuracy: 0.2536 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 7/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2311 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 8/10
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step - accuracy: 0.2371 - loss: nan - val_accuracy: 0.2518 - val_loss: nan
Epoch 9/10
1

In [12]:
loss, acc=model.evaluate(X_test_stan, y_test)
acc

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.2436 - loss: nan


0.2372727245092392

In [13]:
y_test

type_red  type_white
1190       0.0         1.0
2753       1.0         0.0
1558       0.0         1.0
2802       0.0         1.0
2042       1.0         0.0
...        ...         ...
2924       0.0         1.0
2216       0.0         1.0
2761       0.0         1.0
3804       1.0         0.0
2204       1.0         0.0

[1100 rows x 2 columns]

In [14]:
# white=1, red=0인 type_1 column 추출
y_test_c=y_test.iloc[:, 1] # white=1, red=0
y_test_c

1190    1.0
2753    0.0
1558    1.0
2802    1.0
2042    0.0
       ... 
2924    1.0
2216    1.0
2761    1.0
3804    0.0
2204    0.0
Name: type_white, Length: 1100, dtype: float64

In [15]:
# 0.9 이상인 확률은 1, 아닌 경우 0
y_pred=model.predict(X_test_stan)
y_pred_class=np.argmax(y_pred, axis=1)

# confusion matrix
matrix=confusion_matrix(y_test_c, y_pred_class)
matrix

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


array([[261,   0],
       [839,   0]], dtype=int64)

In [16]:
y_pred

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [17]:
(x_train, y_train), (x_test, y_test)=keras.datasets.mnist.load_data()

In [18]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [19]:
img_rows=28
img_cols=28

input_shape=(img_rows, img_cols, 1)

# reshaping mnist dataset
x_train=x_train.reshape(x_train.shape[0], img_rows, img_cols, 1).astype('float32')
x_test=x_test.reshape(x_test.shape[0], img_rows, img_cols, 1).astype('float32')

In [20]:
x_train.shape[0]

60000

In [21]:
x_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [22]:
x_train.max()

255.0

In [23]:
x_train.min()

0.0

In [24]:
# minmax normalize
x_train=x_train/255.
x_test=x_test/255.

In [25]:
y_train=to_categorical(y_train, 10)
y_test=to_categorical(y_test, 10)

In [26]:
model=Sequential()

model.add(Conv2D(64, (3, 3), strides=1, activation='relu', padding='same', input_shape=(28, 28, 1)))
model.add(BatchNormalization())

model.add(Conv2D(32, (3, 3), strides=1, activation='relu', padding='same'))
model.add(BatchNormalization())

model.add(MaxPooling2D((2, 2), strides=2))

# 전결합층 및 Dropout
model.add(layers.Flatten())  # Flatten 레이어로 1차원으로 변환
model.add(layers.Dropout(0.5))  # 노드의 절반만 랜덤하게 선택

# 출력층
model.add(Dense(10, activation='softmax')) # 0부터 9

C:\Users\User\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

TypeError: Trainer.compile() got an unexpected keyword argument 'learning_rate'

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 28, 28, 64)          │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 28, 28, 64)          │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 28, 28, 32)          │          18,464 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 28, 28, 32)          │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 14, 14, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 6272)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 6272)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │          62,730 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 82,218 (321.16 KB)

 Trainable params: 82,026 (320.41 KB)

 Non-trainable params: 192 (768.00 B)

In [29]:
history=model.fit(x_train, y_train, batch_size=32, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 24s 12ms/step - accuracy: 0.8953 - loss: 0.4458
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9694 - loss: 0.1247
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9777 - loss: 0.0859
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9813 - loss: 0.0634
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9846 - loss: 0.0485
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9848 - loss: 0.0436
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9876 - loss: 0.0371
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9880 - loss: 0.0362
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9887 - loss: 0.0322
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.9905 - loss: 0.0287


In [30]:
loss, acc=model.evaluate(x_test, y_test)
acc

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9844 - loss: 0.0490


0.987500011920929

In [31]:
y_pred=model.predict(x_test)
ypred_class=np.argmax(y_pred, axis=1) # 배열에서 가장 큰 값의 인덱스
ytest_class=np.argmax(y_test, axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [32]:
y_pred

array([[1.7914775e-09, 4.1226816e-10, 4.8752565e-07, ..., 9.9996305e-01,
        2.1539780e-07, 2.9486616e-06],
       [8.9330379e-06, 3.2597822e-05, 9.9992311e-01, ..., 1.5439815e-10,
        4.4327098e-08, 2.7651959e-09],
       [2.7521801e-07, 9.9986577e-01, 3.1650632e-08, ..., 2.8998764e-07,
        1.4359964e-05, 1.8261433e-08],
       ...,
       [1.4771425e-13, 7.2632935e-09, 5.6299719e-14, ..., 3.0387913e-08,
        1.3935721e-06, 1.7217813e-07],
       [4.3791637e-10, 3.5691685e-14, 2.6893175e-11, ..., 2.6422922e-10,
        2.8014813e-06, 4.4912651e-09],
       [3.5010405e-08, 7.6100324e-12, 2.0826272e-08, ..., 2.3855484e-13,
        5.6395459e-07, 8.0038758e-09]], dtype=float32)

In [33]:
ypred_class

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [34]:
ytest_class

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [35]:
conf_mat=confusion_matrix(ytest_class, ypred_class)
print(conf_mat)

[[ 975    0    1    1    0    0    1    0    2    0]
 [   0 1131    1    2    0    1    0    0    0    0]
 [   1    8 1011    2    3    0    1    2    4    0]
 [   0    0    0 1007    0    2    0    1    0    0]
 [   0    0    0    0  977    0    2    0    1    2]
 [   1    0    0    9    0  879    1    0    1    1]
 [   3    3    0    0    1    3  946    0    2    0]
 [   0    8    7    3    0    0    0 1002    2    6]
 [   3    0    1    1    1    0    0    0  966    2]
 [   1    2    0    5    8    5    0    1    6  981]]
